- name: Start ngrok tunnel and log RDP info
      run: |
        # Start ngrok in background
        Start-Process -NoNewWindow -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 5  # wait a bit for tunnel to initialize

        # Get public ngrok endpoint
        $retry = 0
        $tcpUrl = ""
        while ($retry -lt 10) {
          try {
            $tunnelStatus = Invoke-RestMethod http://localhost:4040/api/tunnels -ErrorAction SilentlyContinue
            if ($tunnelStatus.tunnels) {
              $tcpUrl = $tunnelStatus.tunnels | Where-Object { $_.proto -eq "tcp" } | Select-Object -ExpandProperty public_url
              if ($tcpUrl) { break }
            }
          } catch { }
          Start-Sleep -Seconds 2
          $retry++
        }

        if (-not $tcpUrl) {
          throw "Could not get ngrok endpoint"
        }

        $rdpAddress = $tcpUrl -replace '^tcp://',''
        Write-Host "==============================================="
        Write-Host "Ngrok RDP Address : $rdpAddress"
        Write-Host "Username          : runneradmin"
        Write-Host "Password          : P@ssw0rd!"
        Write-Host "==============================================="
        Write-Host "ARCHITECT : MUDASIR-YT"

        # Infinite loop to keep workflow alive
        Write-Host "Workflow will now stay alive to keep ngrok tunnel active..."
        while ($true) {
          Start-Sleep -Seconds 300
        }
